memory_simulation : memory_simulation.o
	g++ -o memory_simulation memory_simulation.o

memory_simulation.o : memory_simulation.cpp
	g++ -c -o memory_simulation.o memory_simulation.cpp


clean : 
	rm -f *.o
	rm -f memory_simulation